apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: github-backup
  namespace: aura
  labels:
    team: aura
spec:
  groups:
    - name: github-backup
      rules:
      - alert: GitHub backup failed
        expr: kube_job_failed{job_name=~"^github-backup.*", namespace="aura"} > 0
        for: 1m
        annotations:
          consequence: GitHub repos were not backed up
          action: "`kubectl describe job github-backup`"
          summary: |-
            "The `gitHub-backup` job did not run to completion"
        labels:
          namespace: aura
          severity: warning
