apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: nais
  name:  github-backup
  namespace: nais
spec:
  image: {{ image }}
  schedule: {{ schedule }}
  ttlSecondsAfterFinished: 300
  envFrom:
    - secret: github-backup-config
