apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: aura
  name:  github-backup
  namespace: aura
spec:
  image: {{ image }}
  schedule: {{ schedule }}
  ttlSecondsAfterFinished: 300
  resources:
    limits:
      memory: 2Gi
      cpu: "5"
    requests:
      cpu: "500m"
  env:
    - name: BUCKET_NAME
      value: {{ bucket_name }}
    - name: GODEBUG=http2debug
      value: "1"
  envFrom:
    - secret: github-backup-config
  gcp:
    buckets:
      - name: {{ bucket_name }}
        publicAccessPrevention: true
