apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: nais
  name:  github-backup
  namespace: nais
spec:
  image: {{ image }}
  schedule: "0 2 * * 3,6"
  timeZone: Europe/Oslo
  ttlSecondsAfterFinished: 300
  resources:
    limits:
      memory: 2Gi
      cpu: 5
    requests:
      cpu: 500m
  env:
    - name: BUCKET_NAME
      value: nais-prod-github-repos-backup
  envFrom:
    - secret: github-backup-config
  gcp:
    buckets:
      - name: nais-prod-github-repos-backup
        publicAccessPrevention: true
