name: Monitor dependencies with Snyk
on:
  push:
    branches:
      - main
    paths:
      - "**.gradle.kts"
  workflow_dispatch:
jobs:
  build:
    name: Monitor dependencies with Snyk
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # ratchet:actions/checkout@v2
      - name: Install Snyk CLI
        uses: snyk/actions/setup@4259725f0dd662aa764d82760cca8959888a595c # ratchet:snyk/actions/setup@master
      - name: Monitor dependencies with Snyk
        run: snyk monitor --org=nais
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
